### PR TITLE
Allow child iframe to go fullscreen

### PR DESCRIPTION
**Pull request by lmeyerov**
cc @thibaudh can you check this? the corresponding button is already graph-viz/streamgl master, triggered when in an iframe

### CODE REVIEW

**Comment by lmeyerov** [comment]
Note: without this, the new button does nothing. Force a major version bump as part of the next release?

**Comment by thibaudh** [comment]
Why a major bump? There are no user facing api changes.

**Comment by lmeyerov** [comment]
Well, not sure how to handle. If they use a more recent StreamGL and an old PyGraphistry, they'll see a button that doesn't do anything. (The parent frame will squash the request w/out the explicit permission from this PR.) So, w/out a bump, there's a broken-feeling button.

**Comment by thibaudh** [comment]
We have a warning when the pygraphistry version is not up-to-date. That should help quite a bit. I would rather keep major bump for API overhauls.

**Pull request merged**
