### PR TITLE
Attempt to fix refresh() for SSO

### PR DESCRIPTION
**Pull request by vaimdev**
Refresh in SSO will not display the auth_url due to condition error.
This PR enhance the existing code to throw Token Expire exception and print the correct print out to tell the user that token is expired and required to relogin via SSO.

### CODE REVIEW

**Comment by lmeyerov** [comment]
AFAICT this mostly just changes the exn to being structured, and gives a clearer exn

**Review by lmeyerov — CHANGES_REQUESTED** [review]
see comment

**Comment by vaimdev** [comment]
> AFAICT this mostly just changes the exn to being structured, and gives a clearer exn

I remembered the changes in the PR that fix the bug, this part of code, in the if condition, I removed the   `and not Pygraphistry.api_token()` , which will print the login URL in the case of refresh. Previously, refresh won't enter the `if` block because `Pygraphistry.api_token()` contains old api_token value.  

image

**Review by lmeyerov — APPROVED** [review]
LGTM

To test:
- Run a nexus with this shortened: https://github.com/graphistry/graphistry/blob/30b64d1ed97b8e6b3b634eeb49039bfd558bfeec/compose/dockerfiles/graphistry/nexus/nexus.Dockerfile#L245C5-L245C25
- Setup SSO, including pygraphistry (`graphistry.register(...)`)
- Without patch:
  - first time of `g.plot()`, shows url to login, works
  - after expiry, `g.plot()` should reshow login link... but doesn't

**Pull request merged**
