### PR TITLE
[WIP] Node reductions

### PR DESCRIPTION
**Pull request by pradkrish**
For issue https://github.com/graphistry/pygraphistry/issues/193

### CODE REVIEW

**Comment by pradkrish** [comment]
@lmeyerov Despite this being pretty much a work in progress, I already opened a PR to get some initial feedback. I hope that's okay :)

This is a partial implementation of table reductions. The function `replace_nodes_with_edges(node_selector)` can currently accept both a string and a list of strings. For example the following calls `g.replace_nodes_with_edges(['m']) `and `g.replace_nodes_with_edges('m')` both yield the same results. Here is an example:

```python
g = graphistry.edges(pd.DataFrame([{'x': 'a', 'y': 'm'},
                                   {'x': 'b', 'y': 'm'},
                                   {'x': 'c', 'y': 'n'},
                                   {'x': 'd', 'y': 'm'}]), 'x', 'y')
g.replace_nodes_with_edges(['m',])
print(g._edges)

#result
   x  y reduced_from
0  a  b            m
1  a  d            m
2  b  d            m
3  c  n          NaN

```
What are your thoughts?

**Comment by lmeyerov** [comment]
Cool, some thoughts:

- what happens if `m` is a src, not dst?
- how about specify nodes as a `Series`, say 1-column or if multi-column, index on `g._node`? ex: user might pick `g._nodes[ g._nodes['type'] == 'account' ]`
- `reduced_from` right now (afaict) would report `"m,n,o,p"` instead of `"m"` when used on a list input

I'll need to look at `itertools`, but the rest seems straightforward to port to `cudf` / `dask_cudf` :)

**Comment by pradkrish** [comment]
@lmeyerov  Thank you very much for your feedback. I have pushed another commit now. Kindly have a look at the `replace_nodes_with_edges(..)` function comments, it should address some of the issues your raised. I have also added some tests to show how to use this function. As far itertools, I have replaced the logic which now uses `numpy.tril`. Please have a look and let me know what you think. :)

**Comment by lmeyerov** [comment]
Great!

In case it helped, I sketched out a few the top use cases we see in the original ticket: https://github.com/graphistry/pygraphistry/issues/193  

re:`tril`, I'm struggling to understand that logic, which suggests someone doing a future bugfix here would need to rewrite it.. can it be something like `pd.concat`? I'm guessing once the aggregation operators come in and more tests, we'll have a better sense of what needs to be fast/slow, so simple vector pd calls should get us far..

**Comment by lmeyerov** [comment]
Just checking in on this. Maybe the thing to do is:

- make sure each of the motivating examples is in a test
- test a few different tricky graph shapes

I'm thinking we can land this as-is, and update the underlying feature request to more carefully explore (a) a custom reductions mode for this and (b) multi-node collapsing/grouping

**Pull request closed without merging**
